In [35]:
import numpy as np
data_set1 = np.arange(1,10)
data_set2 = np.random.randint(10, size = (3,3))
print("Завдання 1. NumPy")
print()
print("Набір даних, функція arrange:")
print(data_set1)
print("Набір даних, функція random:")
print(data_set2)
arr = np.save('data_set1.npy',data_set1)
output = np.load('data_set1.npy')
print("Зчитування з файлу:", output)
print()
print("Операції:скаляр, вектор, матриця")
print()
print ("Множення матриці на скаляр: ")
print (3*data_set2)
print ("Транспонування матриці: ")
print (np.transpose(data_set2))
numpy_array_1 = np.array([40, 50, 60])
numpy_array_2 = np.array([10, 20, 30])
print ("Сума двох векторів:")
print (np.add(numpy_array_1,numpy_array_2))
print ("Добуток векторів: ")
print (np.dot(numpy_array_1,numpy_array_2))
vector = np.arange(1,11)
print("Початковий вектор:")
print(data_set1)
vector_new = np.delete(data_set1,[1,2])
print("Видалення елементів:")
print(vector_new)

Завдання 1. NumPy

Набір даних, функція arrange:
[1 2 3 4 5 6 7 8 9]
Набір даних, функція random:
[[6 8 4]
 [1 2 9]
 [2 2 2]]
Зчитування з файлу: [1 2 3 4 5 6 7 8 9]

Операції:скаляр, вектор, матриця

Множення матриці на скаляр: 
[[18 24 12]
 [ 3  6 27]
 [ 6  6  6]]
Транспонування матриці: 
[[6 1 2]
 [8 2 2]
 [4 9 2]]
Сума двох векторів:
[50 70 90]
Добуток векторів: 
3200
Початковий вектор:
[1 2 3 4 5 6 7 8 9]
Видалення елементів:
[1 4 5 6 7 8 9]
