In [1]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

Matplotlib is building the font cache; this may take a moment.


In [2]:
mark = ['Mercedes','Mercedes','Mercedes','Opel','Opel','Opel','Opel','Honda','Honda','Honda','Honda','Honda']
price = ['9000','15500','13300','4000','12000','9500','4000','11300','13000','9400','5000','7000']
mileage = ['12390','5700','8660','23305','1487','6547','14700','5100','3900','3408','7420','1600']
data_frame = pd.DataFrame({'mark':mark,'price':price,'mileage':mileage})
print(data_frame)

        mark  price mileage
0   Mercedes   9000   12390
1   Mercedes  15500    5700
2   Mercedes  13300    8660
3       Opel   4000   23305
4       Opel  12000    1487
5       Opel   9500    6547
6       Opel   4000   14700
7      Honda  11300    5100
8      Honda  13000    3900
9      Honda   9400    3408
10     Honda   5000    7420
11     Honda   7000    1600


In [3]:
leble = LabelEncoder()
Num_mark = data_frame[data_frame.columns[:1]].apply(leble.fit_transform)
data_frame.mark = Num_mark

In [4]:
mixed_data_frame = data_frame.sample(frac=1)
print(mixed_data_frame)

    mark  price mileage
5      2   9500    6547
0      1   9000   12390
1      1  15500    5700
10     0   5000    7420
11     0   7000    1600
6      2   4000   14700
2      1  13300    8660
7      0  11300    5100
8      0  13000    3900
3      2   4000   23305
9      0   9400    3408
4      2  12000    1487


In [5]:
piece = int(0.7*len(data_frame))
train_data = mixed_data_frame.iloc[:piece,:]
piece = int(0.3*len(data_frame))
test_data = mixed_data_frame.iloc[:piece,:]
train_x = train_data[train_data.columns[:2]]
train_y = train_data[train_data.columns[2:]]
test_x = test_data[test_data.columns[:2]]
test_y = test_data[test_data.columns[2:]]

In [6]:
model = LinearRegression(fit_intercept = True, normalize = True)
reg = model.fit(train_x,train_y)

In [7]:
pred_y = reg.predict(test_x)
print("Predict is : \n",pred_y)
print("In data frame is: \n", test_y)

Predict is : 
 [[11108.78479081]
 [ 8247.98428398]
 [ 6138.47477678]]
In data frame is: 
   mileage
5    6547
0   12390
1    5700


In [8]:
reg.coef_

array([[ 3.02307047e+03, -3.24539924e-01]])

In [9]:
reg.intercept_

array([8145.77313271])